// ===== PES3 ACADEMY v1.2 =====
const ACADEMY=[
['UMPAN & BUILD-UP','Umpan Pendek Aman','X + arah','pass','Hadapkan badan ke penerima dan pastikan jalur bersih.','1. Kontrol badan\n2. Lihat jalur\n3. X ke rekan\n4. Bergerak lagi mencari sudut','Dua umpan aman lalu satu umpan tajam.','PASS COMPLETE'],
['UMPAN & BUILD-UP','Through Pass','△ + arah','through','Kirim bola ke ruang di depan runner.','1. Tunggu runner mulai lari\n2. △ ke ruang\n3. Lepas sebelum CB berbalik','Jangan arahkan ke kaki; arahkan ke ruang.','BREAK THE LINE'],
['UMPAN & BUILD-UP','Lofted Through Ball','L1 + △','loft','Lewati high defensive line dengan bola lambung.','1. Runner mulai sprint\n2. L1 + △\n3. Kalibrasi power','Variasikan; jangan spam lofted through.','RUN IN BEHIND'],
['UMPAN & BUILD-UP','One-Two','L1 + X → X/△','oneTwo','Pengumpan pertama langsung melakukan run setelah memberi bola.','1. L1 + X\n2. Gerakkan runner\n3. Balikkan X/△','Jika bek mengikuti runner, pemain kedua boleh terus membawa bola.','ONE-TWO COMPLETE'],
['UMPAN & BUILD-UP','Switch Play','O + arah sisi jauh','switch','Pindahkan bola ke sisi kosong ketika lawan overload satu sisi.','1. Tarik lawan\n2. Buka badan DMF/CMF\n3. O ke sisi jauh','Switch hanya jika pengumpan tidak ditekan.','SWITCH SUCCESS'],
['UMPAN & BUILD-UP','Crossing Rendah','O dua kali','crossLow','Cross rendah ke celah CB-GK.','1. Capai area crossing\n2. Lihat run CF\n3. O dua kali cepat','Ideal saat CF sudah unggul setengah langkah.','CUTBACK CHANCE'],
['UMPAN & BUILD-UP','Crossing Tinggi','O + power','crossHigh','Cross tinggi untuk target heading di kotak.','1. Ambil ruang di sayap\n2. O secukupnya\n3. Arahkan target lari','Jangan crossing ketika CF statis di belakang CB.','AERIAL CHANCE'],
['SHOOTING & FINISHING','Normal Shot','□ + arah','shot','Tembakan dasar dari posisi stabil.','1. Lepas sprint\n2. Arahkan sudut\n3. □ power sedang','Di dalam kotak, power berlebihan sering mengurangi kontrol.','GOAL!'],
['SHOOTING & FINISHING','Controlled / Curl Shot','R2 + □','curl','Tembakan terarah ke tiang jauh.','1. Bawa ke kaki dominan\n2. Bidik far post\n3. R2 + □','Gunakan saat ada sepersekian detik ruang.','TOP CORNER'],
['SHOOTING & FINISHING','Chip Shot','L1 + □','chip','Cungkil bola saat kiper sudah maju.','1. Tunggu GK keluar\n2. L1 + □\n3. Power ringan-menengah','Jangan chip terlalu dini.','CHIP GOAL'],
['SHOOTING & FINISHING','First-Time Shot','□ sebelum bola tiba','firstTime','Finishing satu sentuhan dari cutback/cross.','1. Arahkan badan\n2. □ sebelum bola tiba\n3. Power moderat','Lebih cepat daripada kontrol saat ruang sempit.','FIRST-TIME GOAL'],
['SHOOTING & FINISHING','Fake Shot → Finish','□ lalu X → □','fakeShot','Buat defender bereaksi lalu ubah sudut tembak.','1. □ lalu X\n2. Potong arah\n3. □ lagi','Jangan spam fake shot.','DEFENDER BEATEN'],
['SHOOTING & FINISHING','Long Shot','□ 55–75%','longShot','Tembakan dari luar kotak ketika ruang terbuka.','1. Set badan\n2. Jangan sambil berputar\n3. □ power lebih tinggi','Pilih pemain dengan kicking power bagus.','LONG-RANGE THREAT'],
['SHOOTING & FINISHING','Near-Post Finish','□ + arah tiang dekat','shot','Selesaikan cepat ketika kiper terlalu menjaga far post.','1. Masuk diagonal\n2. Lihat posisi GK\n3. □ ke near post','Baca kiper, jangan selalu far post.','NEAR-POST GOAL'],
['BERTAHAN & MEREBUT BOLA','Jockey & Tutup Jalur','Arah + X seperlunya','jockey','Mundur mengikuti lawan dan paksa ke arah luar.','1. Jaga jarak\n2. Tutup tengah\n3. X saat sentuhan lawan menjauh','Jangan tahan R1+X terus.','BALL WON'],
['BERTAHAN & MEREBUT BOLA','Intercept Passing Lane','Arah manual + X','intercept','Baca tujuan umpan dan berdiri di garis passing.','1. Pilih DMF\n2. Potong jalur\n3. Bergerak saat bola dilepas','Intersep menjaga shape lebih baik daripada mengejar bola.','INTERCEPTED'],
['BERTAHAN & MEREBUT BOLA','Second-Man Pressure','□ tahan + kontrol pemain utama','secondPress','Rekan menekan, kamu menutup penerima berbahaya.','1. Tahan □\n2. Pemain utama cover lane\n3. Lepas □ jika shape rusak','Jangan biarkan dua pemain mengejar orang yang sama.','TRAP SUCCESS'],
['BERTAHAN & MEREBUT BOLA','Standing Tackle Timing','X saat bola menjauh','tackle','Tackle berdiri ketika lawan melakukan heavy touch.','1. Dekati tanpa overrun\n2. Tunggu bola lepas\n3. X sekali','Spam X meningkatkan risiko foul dan out of position.','CLEAN TACKLE'],
['BERTAHAN & MEREBUT BOLA','Sliding Tackle','O','slide','Sliding hanya ketika bola jelas bisa dijangkau.','1. Sejajarkan arah\n2. O pada bola\n3. Hindari dari belakang','High-risk tool; jangan jadi tombol default.','SLIDE WON'],
['BERTAHAN & MEREBUT BOLA','Stop Counter dengan DMF','DMF manual dulu','defendCounter','Perlambat counter tanpa menarik CB keluar.','1. Pilih DMF\n2. Tutup jalur ke CF\n3. CB tetap sejajar','Delay satu detik memberi waktu tim turun.','COUNTER STOPPED'],
['BERTAHAN & MEREBUT BOLA','Block Crossing','Arah manual + X','blockCross','Tutup kaki crossing winger sebelum mengirim bola.','1. Jangan dive in\n2. Jaga sisi dalam\n3. Dekati saat winger menyiapkan kaki','Memblok cross lebih aman daripada duel udara setelah bola masuk.','CROSS BLOCKED'],
['BERTAHAN & MEREBUT BOLA','Clearance Darurat','□ / O','clear','Buang bola ke sisi saat build-up terlalu berisiko.','1. Jangan paksa short pass\n2. Arahkan ke sayap\n3. □/O','Lebih baik kehilangan bola di sayap daripada di depan gawang.','DANGER CLEARED'],
['SEPAK POJOK','Near Post Corner','O + arah near post','cornerNear','Cross ke pelari tiang dekat.','1. Bidik 6-yard near post\n2. O power sedang\n3. Runner mendahului CB','Gunakan target dengan heading/jump kuat.','HEADER CHANCE'],
['SEPAK POJOK','Far Post Corner','O + arah far post','cornerFar','Cross panjang ke target belakang.','1. Bidik far post\n2. Tambah power\n3. Runner datang dari belakang','Bagus ketika lawan menumpuk near post.','FAR-POST HEADER'],
['SEPAK POJOK','Short Corner','X ke pemain dekat','shortCorner','Buat 2v1 dan sudut crossing baru.','1. X pendek\n2. One-two/dribble\n3. Cross/cutback','Efektif melawan CB tinggi.','2v1 CREATED'],
['SEPAK POJOK','Corner Rendah / Cutback','O dua kali / short + X','cornerCutback','Cari CMF di tepi kotak, bukan kerumunan.','1. Tarik penjaga\n2. Bola rendah ke cutback\n3. First-time/reset','Membuat defender memutar badan.','CUTBACK OPEN'],
['SEPAK POJOK','Edge-of-Box Routine','X pendek → umpan ke CMF','cornerCutback','Skema bola mati untuk tembakan dari luar kotak.','1. Short corner\n2. Tarik bek\n3. Pass ke CMF bebas','Jangan tembak jika lane tertutup; reset lebih baik.','SHOOTING LANE'],
['TENDANGAN BEBAS','Free Kick Curve','□ + arah/curve','freeCurve','Lengkungkan bola melewati sisi pagar.','1. Bidik sedikit di luar pagar\n2. □ power sedang\n3. Beri arah lengkung','Atribut curl eksekutor sangat berpengaruh.','CURVE GOAL'],
['TENDANGAN BEBAS','Free Kick Power','□ + power lebih besar','freePower','Tendangan keras untuk jarak menengah-jauh.','1. Pilih power kicker\n2. Bidik aman\n3. □ 50–70% sesuai jarak','Kalibrasi power, jangan selalu full.','POWER SHOT'],
['TENDANGAN BEBAS','Free Kick Rendah','□ + arah bawah','freeLow','Tendangan rendah untuk mengejutkan pagar/kiper.','1. Bidik sudut bawah\n2. Power rendah-menengah\n3. Tahan arah bawah','Efektif jika lawan suka melompatkan pagar.','LOW FREE KICK'],
['TENDANGAN BEBAS','Free Kick Umpan','X ke rekan','freePass','Gunakan bola mati sebagai skema passing.','1. Siapkan rekan\n2. X pendek\n3. Third-man run','Variasi pendek membuat pagar lawan ragu.','SET-PIECE MOVE'],
['TENDANGAN BEBAS','Far-Post Delivery','O / cross ke far post','cornerFar','Bola bebas dari sisi untuk target far post.','1. Arahkan target\n2. Cross ke belakang garis\n3. Header kembali/ke gawang','Jangan selalu langsung shot dari sudut sempit.','FAR-POST BALL'],
['DRIBBLE & KONTROL','Fake Shot','□ lalu X','dribbleFake','Batalkan shot/cross untuk potong arah.','1. Dekati defender\n2. □ lalu X\n3. Arahkan ruang baru','Efektif saat lawan commit.','SPACE CREATED'],
['DRIBBLE & KONTROL','Super Cancel','R1 + R2','superCancel','Ambil alih jalur lari otomatis.','1. R1 + R2\n2. Gerak manual\n3. Lepas saat posisi unggul','Kuat untuk bola lepas dan crossing.','MANUAL POSITION WON'],
['DRIBBLE & KONTROL','Sprint Timing','R1 setelah ruang terbuka','sprint','Terima bola dulu, baru sprint.','1. First touch tanpa R1\n2. Buka badan\n3. R1','Sprint terus membuat bola jauh dari kaki.','CLEAN ACCELERATION'],
['DRIBBLE & KONTROL','Body Orientation','Analog kiri → X/△','body','Putar badan sebelum passing.','1. Terima bola\n2. Putar 30–90°\n3. Pass','Satu sentuhan ekstra yang benar mengurangi intersep.','PASSING LANE OPEN'],
['DRIBBLE & KONTROL','Change of Direction','Analog kiri + lepas sprint','dribbleFake','Ubah arah ketika defender berkomitmen.','1. Dekati tanpa full sprint\n2. Lepas R1\n3. Potong arah','Timing lebih penting daripada skill move rumit.','DEFENDER WRONG-FOOTED'],
['KIPER & PENALTI','GK Rush 1v1','△ tahan','gkRush','Keluarkan kiper untuk mempersempit sudut.','1. Tunggu striker lepas\n2. △ tahan\n3. Lepas jika lawan siap chip','Jangan terlalu dini.','ANGLE CLOSED'],
['KIPER & PENALTI','Penalty Normal','Arah + □','penalty','Tentukan sisi dan power yang konsisten.','1. Pilih sisi\n2. Arah + □\n3. Hindari power berlebihan','Konsistensi > sudut ekstrem.','PENALTY GOAL'],
['KIPER & PENALTI','Panenka','L1 + □','panenka','Chip penalti saat kiper bergerak dulu.','1. Baca kiper\n2. L1 + □\n3. Power ringan-menengah','Jangan dipakai jika lawan suka diam di tengah.','PANENKA'],
['KIPER & PENALTI','Menebak Penalti','Arah kiper pada timing','penaltySave','Tahan posisi sampai mendekati momen tendangan, lalu pilih sisi.','1. Amati penendang\n2. Jangan bergerak terlalu dini\n3. Pilih sisi','Lawan manusia bisa membaca kebiasaan dive-mu juga.','SAVE!']
].map(x=>({cat:x[0],title:x[1],buttons:x[2],kind:x[3],desc:x[4],steps:x[5],tip:x[6],result:x[7]}));
const acat=$('academyCat'),adrill=$('academyDrill'),apitch=$('academyPitch'),aactors=$('academyActors'),aball=$('academyBall'),aroute=$('academyRoute'),abadge=$('academyBadge'),aresult=$('academyResult'),ainfo=$('academyInfo');let academyRAF=null,academyScenario=null,academyLayout=null;
const ACATS=[...new Set(ACADEMY.map(x=>x.cat))];ACATS.forEach(x=>acat.add(new Option(x,x)));
function academyLayoutFor(k){
 const U=(id,l,x,y)=>[id,l,'user',x,y],T=(id,l,x,y)=>[id,l,'team',x,y],O=(id,l,x,y)=>[id,l,'opp',x,y],G=(id,l,x,y)=>[id,l,'gk',x,y],B=(x,y)=>['ball','','ball',x,y],M=(id,fx,fy,tx,ty,s,e,l,arc=false)=>({id,fx,fy,tx,ty,s,e,l,arc});
 const table={
 pass:[[U('p1','P1',.52,.76),T('p2','P2',.33,.49),O('o1','O1',.58,.57),B(.52,.76)],[M('p1',.52,.76,.48,.70,0,.2,'BUKA BADAN'),M('ball',.52,.76,.33,.49,.2,.58,'X • SHORT PASS'),M('p2',.33,.49,.29,.42,.56,.9,'SUPPORT')]],
 through:[[U('p1','AMF',.5,.62),T('p2','CF',.45,.34),O('o1','CB',.53,.4),O('o2','CB',.67,.42),B(.5,.62)],[M('p2',.45,.34,.37,.16,.05,.62,'DIAGONAL RUN'),M('ball',.5,.62,.37,.17,.22,.64,'△ • THROUGH')]],
 loft:[[U('p1','CMF',.48,.66),T('p2','RWF',.78,.36),O('o1','CB',.56,.4),O('o2','LB',.77,.43),B(.48,.66)],[M('p2',.78,.36,.74,.14,.05,.7,'SPRINT'),M('ball',.48,.66,.74,.16,.2,.7,'L1+△ • LOFT',true)]],
 oneTwo:[[U('p1','AMF',.42,.61),T('p2','CF',.56,.4),O('o1','DMF',.5,.5),O('o2','CB',.58,.3),B(.42,.61)],[M('ball',.42,.61,.56,.4,.08,.35,'L1+X'),M('p1',.42,.61,.38,.28,.24,.7,'RUNNER'),M('ball',.56,.4,.38,.29,.43,.75,'X/△ • RETURN')]],
 switch:[[U('p1','DMF',.28,.64),T('p2','RWF',.84,.34),O('o1','O1',.29,.48),O('o2','O2',.42,.46),B(.28,.64)],[M('ball',.28,.64,.84,.34,.18,.72,'O • SWITCH',true),M('p2',.84,.34,.81,.25,.62,.94,'FIRST TOUCH')]],
 crossLow:[[U('p1','RWF',.87,.31),T('p2','CF',.53,.25),O('o1','CB',.6,.25),G('gk','GK',.5,.08),B(.87,.31)],[M('p2',.53,.25,.46,.18,.1,.6,'RUN'),M('ball',.87,.31,.46,.18,.36,.69,'O×2 • LOW CROSS')]],
 crossHigh:[[U('p1','RWF',.87,.31),T('p2','CF',.48,.24),O('o1','CB',.57,.23),G('gk','GK',.5,.08),B(.87,.31)],[M('p2',.48,.24,.42,.14,.1,.62,'ATTACK BALL'),M('ball',.87,.31,.42,.14,.28,.72,'O • HIGH CROSS',true)]],
 shot:[[U('p1','CF',.5,.34),O('o1','CB',.64,.34),G('gk','GK',.5,.08),B(.5,.34)],[M('p1',.5,.34,.47,.29,0,.25,'SET BODY'),M('ball',.5,.34,.37,.07,.28,.72,'□ • SHOOT'),M('gk',.5,.08,.45,.1,.48,.72,'GK DIVE')]],
 curl:[[U('p1','LWF',.3,.3),O('o1','CB',.45,.27),G('gk','GK',.5,.08),B(.3,.3)],[M('ball',.3,.3,.62,.07,.24,.76,'R2+□ • CURL',true),M('gk',.5,.08,.58,.1,.52,.78,'GK DIVE')]],
 chip:[[U('p1','CF',.5,.35),G('gk','GK',.5,.18),B(.5,.35)],[M('gk',.5,.18,.5,.27,0,.35,'GK RUSH'),M('ball',.5,.35,.54,.07,.3,.78,'L1+□ • CHIP',true)]],
 firstTime:[[T('p1','RWF',.82,.33),U('p2','CF',.48,.24),O('o1','CB',.58,.25),G('gk','GK',.5,.08),B(.82,.33)],[M('ball',.82,.33,.48,.24,.1,.46,'CUTBACK'),M('ball',.48,.24,.38,.07,.48,.78,'□ • FIRST-TIME')]],
 fakeShot:[[U('p1','CF',.48,.31),O('o1','CB',.5,.24),G('gk','GK',.5,.08),B(.48,.31)],[M('p1',.48,.31,.4,.27,.12,.43,'□→X • FAKE'),M('ball',.48,.31,.4,.27,.12,.43,'FAKE TOUCH'),M('o1',.5,.24,.47,.29,.15,.46,'DEFENDER BITES'),M('ball',.4,.27,.58,.07,.48,.82,'□ • FINISH')]],
 longShot:[[U('p1','CMF',.51,.47),O('o1','DMF',.63,.44),G('gk','GK',.5,.08),B(.51,.47)],[M('p1',.51,.47,.5,.42,0,.25,'SET FEET'),M('ball',.51,.47,.34,.07,.28,.8,'□ • POWER SHOT',true)]],
 jockey:[[U('p1','DMF',.5,.67),O('o1','AMF',.43,.39),B(.43,.39)],[M('o1',.43,.39,.56,.58,0,.62,'OPP DRIBBLE'),M('ball',.43,.39,.56,.58,0,.62,'BALL'),M('p1',.5,.67,.55,.6,.08,.6,'JOCKEY'),M('ball',.56,.58,.55,.6,.64,.82,'X • TACKLE')]],
 intercept:[[U('p1','DMF',.5,.6),O('o1','CMF',.31,.46),O('o2','CF',.63,.29),B(.31,.46)],[M('p1',.5,.6,.49,.46,.1,.55,'CUT LANE'),M('ball',.31,.46,.63,.29,.3,.72,'OPP PASS'),M('ball',.49,.46,.49,.46,.56,.68,'INTERCEPT')]],
 secondPress:[[U('p1','DMF',.55,.61),T('p2','CMF',.33,.6),O('o1','AMF',.43,.42),O('o2','CF',.64,.27),B(.43,.42)],[M('p2',.33,.6,.41,.46,.05,.55,'□ • PRESS'),M('p1',.55,.61,.6,.43,.05,.55,'COVER LANE'),M('o1',.43,.42,.45,.47,.1,.6,'FORCED SIDE'),M('ball',.43,.42,.41,.46,.58,.76,'WIN BALL')]],
 tackle:[[U('p1','CB',.51,.61),O('o1','CF',.48,.4),B(.48,.4)],[M('o1',.48,.4,.52,.55,0,.58,'HEAVY TOUCH'),M('ball',.48,.4,.54,.58,0,.6,'BALL'),M('p1',.51,.61,.53,.58,.46,.69,'X • TACKLE'),M('ball',.54,.58,.5,.65,.68,.86,'RECOVER')]],
 slide:[[U('p1','RB',.65,.65),O('o1','LWF',.62,.39),B(.62,.39)],[M('o1',.62,.39,.68,.57,0,.6,'SPRINT'),M('ball',.62,.39,.7,.59,0,.6,'BALL'),M('p1',.65,.65,.69,.59,.45,.68,'O • SLIDE'),M('ball',.7,.59,.57,.66,.66,.84,'CLEAR')]],
 defendCounter:[[U('p1','DMF',.49,.62),T('p2','CB',.39,.75),T('p3','CB',.61,.75),O('o1','AMF',.52,.43),O('o2','CF',.5,.24),B(.52,.43)],[M('p1',.49,.62,.5,.48,.02,.55,'DMF DELAY'),M('o1',.52,.43,.55,.49,.05,.6,'COUNTER'),M('ball',.52,.43,.5,.48,.6,.78,'INTERCEPT')]],
 blockCross:[[U('p1','RB',.72,.55),O('o1','LWF',.79,.35),T('p2','CB',.52,.25),B(.79,.35)],[M('o1',.79,.35,.82,.48,0,.55,'WINGER SETS'),M('ball',.79,.35,.82,.48,0,.55,'BALL'),M('p1',.72,.55,.8,.48,.18,.62,'CLOSE DOWN'),M('ball',.82,.48,.78,.51,.62,.78,'BLOCK')]],
 clear:[[U('p1','CB',.48,.76),O('o1','CF',.52,.64),B(.48,.76)],[M('o1',.52,.64,.5,.71,.05,.45,'PRESS'),M('ball',.48,.76,.16,.35,.36,.8,'□/O • CLEAR',true)]],
 cornerNear:[[U('p1','CK',.08,.08),T('p2','CF',.4,.22),O('o1','CB',.46,.2),G('gk','GK',.5,.07),B(.08,.08)],[M('p2',.4,.22,.37,.13,.08,.58,'NEAR RUN'),M('ball',.08,.08,.37,.13,.22,.67,'O • CORNER',true)]],
 cornerFar:[[U('p1','CK',.08,.08),T('p2','CB',.7,.22),O('o1','CB',.58,.18),G('gk','GK',.5,.07),B(.08,.08)],[M('p2',.7,.22,.65,.12,.08,.63,'FAR RUN'),M('ball',.08,.08,.65,.12,.18,.72,'O • FAR POST',true)]],
 shortCorner:[[U('p1','CK',.08,.08),T('p2','W',.17,.22),O('o1','LB',.29,.2),B(.08,.08)],[M('ball',.08,.08,.17,.22,.12,.36,'X • SHORT'),M('p1',.08,.08,.19,.14,.28,.67,'OVERLAP'),M('ball',.17,.22,.19,.14,.58,.8,'RETURN')]],
 cornerCutback:[[U('p1','CK',.08,.08),T('p2','CMF',.46,.36),O('o1','CB',.42,.2),B(.08,.08)],[M('ball',.08,.08,.46,.36,.18,.62,'LOW CUTBACK'),M('p2',.46,.36,.5,.31,.54,.83,'SET TO SHOOT')]],
 freeCurve:[[U('p1','FK',.49,.54),O('w1','W',.38,.3),O('w2','W',.46,.29),O('w3','W',.54,.29),O('w4','W',.62,.3),G('gk','GK',.55,.08),B(.49,.54)],[M('ball',.49,.54,.36,.07,.22,.78,'CURVED FREE KICK',true),M('gk',.55,.08,.47,.1,.55,.78,'GK DIVE')]],
 freePower:[[U('p1','FK',.49,.54),O('w1','W',.42,.3),O('w2','W',.5,.29),O('w3','W',.58,.3),G('gk','GK',.52,.08),B(.49,.54)],[M('ball',.49,.54,.62,.07,.18,.7,'POWER FREE KICK',true)]],
 freeLow:[[U('p1','FK',.49,.54),O('w1','W',.42,.3),O('w2','W',.5,.29),O('w3','W',.58,.3),G('gk','GK',.52,.08),B(.49,.54)],[M('ball',.49,.54,.42,.08,.22,.74,'LOW FREE KICK')]],
 freePass:[[U('p1','FK',.48,.54),T('p2','AMF',.67,.46),T('p3','CF',.56,.23),O('o1','W',.48,.3),O('o2','CB',.6,.27),B(.48,.54)],[M('ball',.48,.54,.67,.46,.18,.43,'X • LAYOFF'),M('p3',.56,.23,.49,.15,.35,.72,'RUN'),M('ball',.67,.46,.49,.16,.48,.8,'△ • FINAL PASS')]],
 dribbleFake:[[U('p1','W',.36,.5),O('o1','FB',.48,.42),B(.36,.5)],[M('p1',.36,.5,.5,.47,.08,.34,'APPROACH'),M('ball',.36,.5,.5,.47,.08,.34,'BALL'),M('o1',.48,.42,.46,.49,.25,.5,'COMMITS'),M('p1',.5,.47,.39,.36,.38,.76,'□→X • CUT'),M('ball',.5,.47,.39,.36,.38,.76,'FAKE SHOT')]],
 superCancel:[[U('p1','CF',.48,.38),O('o1','CB',.55,.33),B(.3,.52)],[M('ball',.3,.52,.58,.24,.08,.66,'LOOSE BALL',true),M('p1',.48,.38,.61,.27,.12,.64,'R1+R2 • MANUAL'),M('o1',.55,.33,.56,.29,.12,.58,'AUTO TRACK')]],
 sprint:[[U('p1','W',.3,.58),O('o1','FB',.46,.48),B(.3,.58)],[M('p1',.3,.58,.33,.52,.05,.3,'CONTROL'),M('ball',.3,.58,.33,.52,.05,.3,'TOUCH'),M('p1',.33,.52,.58,.3,.34,.82,'R1 • SPRINT'),M('ball',.33,.52,.58,.3,.34,.82,'KNOCK-ON')]],
 body:[[U('p1','CMF',.5,.62),T('p2','AMF',.57,.38),O('o1','DMF',.51,.48),B(.5,.62)],[M('p1',.5,.62,.45,.58,.06,.34,'OPEN BODY'),M('ball',.5,.62,.45,.58,.06,.34,'CONTROL'),M('ball',.45,.58,.57,.38,.36,.72,'X • PASS')]],
 gkRush:[[G('gk','GK',.5,.09),O('o1','CF',.5,.4),B(.5,.4)],[M('o1',.5,.4,.52,.24,0,.62,'BREAKAWAY'),M('ball',.5,.4,.52,.24,0,.62,'BALL'),M('gk',.5,.09,.51,.22,.15,.6,'△ • GK RUSH'),M('ball',.52,.24,.51,.22,.64,.8,'SMOTHER')]],
 penalty:[[U('p1','PK',.5,.38),G('gk','GK',.5,.08),B(.5,.38)],[M('ball',.5,.38,.35,.07,.25,.72,'□ • PENALTY'),M('gk',.5,.08,.58,.09,.46,.72,'GK GUESSES')]],
 panenka:[[U('p1','PK',.5,.38),G('gk','GK',.5,.08),B(.5,.38)],[M('gk',.5,.08,.35,.08,.22,.6,'GK DIVE'),M('ball',.5,.38,.5,.07,.28,.76,'L1+□ • CHIP',true)]],
 penaltySave:[[G('gk','GK',.5,.08),O('o1','PK',.5,.38),B(.5,.38)],[M('ball',.5,.38,.65,.07,.28,.72,'OPP PENALTY'),M('gk',.5,.08,.63,.09,.42,.72,'DIVE RIGHT')]]
 };return table[k]||table.pass;
}
function academyLoadCat(){adrill.innerHTML='';ACADEMY.filter(x=>x.cat===acat.value).forEach((x,i)=>adrill.add(new Option(x.title,i)));adrill.value='0';academyLoad();}
function academyLoad(){const list=ACADEMY.filter(x=>x.cat===acat.value);academyScenario=list[+adrill.value||0]||list[0];academyLayout=academyLayoutFor(academyScenario.kind);academyReset();ainfo.innerHTML=`<h3>${academyScenario.title}</h3><div class="keys">🎮 ${academyScenario.buttons}</div><div>${academyScenario.desc}</div><br><b>LANGKAH</b><div class="steps">${academyScenario.steps}</div><br><b>⚡ COACH TIP</b><div>${academyScenario.tip}</div>`;}
function academyPos(actor,t){let x=actor[3],y=actor[4];for(const m of academyLayout[1]){if(m.id!==actor[0])continue;if(t<m.s)break;if(t>=m.e){x=m.tx;y=m.ty;continue}let u=(t-m.s)/(m.e-m.s);u=u*u*(3-2*u);x=m.fx+(m.tx-m.fx)*u;y=m.fy+(m.ty-m.fy)*u;if(m.arc)y-=Math.sin(Math.PI*u)*.08;break}return{x,y}}
function academyRender(t=-1){const w=apitch.clientWidth,h=apitch.clientHeight;aroute.setAttribute('viewBox',`0 0 ${w} ${h}`);aroute.innerHTML='';for(const m of academyLayout[1]){if(m.id!=='ball')continue;const path=document.createElementNS('http://www.w3.org/2000/svg','path');let d=`M ${m.fx*w} ${m.fy*h} `;d+=m.arc?`Q ${(m.fx+m.tx)*w/2} ${Math.min(m.fy,m.ty)*h-28} ${m.tx*w} ${m.ty*h}`:`L ${m.tx*w} ${m.ty*h}`;path.setAttribute('d',d);path.setAttribute('fill','none');path.setAttribute('stroke','#ffffff55');path.setAttribute('stroke-width','1.7');path.setAttribute('stroke-dasharray','6 7');aroute.appendChild(path)}
 aactors.innerHTML='';for(const a of academyLayout[0]){if(a[2]==='ball')continue;const q=academyPos(a,t<0?0:t),el=document.createElement('div');el.className=`academyActor ${a[2]}`;el.style.left=q.x*100+'%';el.style.top=q.y*100+'%';el.innerHTML=`<div class="adot">${a[1]}</div><div class="alabel">${a[1]}</div>`;aactors.appendChild(el)}const ballActor=academyLayout[0].find(a=>a[2]==='ball');if(ballActor){const q=academyPos(ballActor,t<0?0:t);aball.style.display='block';aball.style.left=q.x*100+'%';aball.style.top=q.y*100+'%'}
 let label='READY';if(t>=0){const active=academyLayout[1].find(m=>t>=m.s&&t<=m.e);label=active?active.l:(t>.86?academyScenario.result:academyScenario.title)}abadge.textContent=label;aresult.textContent=academyScenario.result;aresult.style.display=t>.86?'block':'none';}
function academyPlay(){if(academyRAF)cancelAnimationFrame(academyRAF);const start=performance.now(),dur=6000;function f(now){const t=Math.min(1,(now-start)/dur);academyRender(t);if(t<1)academyRAF=requestAnimationFrame(f);else academyRAF=null}academyRAF=requestAnimationFrame(f)}
function academyReset(){if(academyRAF)cancelAnimationFrame(academyRAF);academyRAF=null;academyRender(-1)}
acat.onchange=academyLoadCat;adrill.onchange=academyLoad;$('academyPlay').onclick=academyPlay;$('academyReset').onclick=academyReset;acat.value=ACATS[0];academyLoadCat();window.addEventListener('resize',()=>academyScenario&&academyRender(-1));

TEAMS.forEach(t=>team.add(new Option(t.name,t.name)));team.value='Bayern Munich';$('counter').textContent=`${TEAMS.length*(TEMPLATES.length+1)} preset • ${TEAMS.length} tim/negara • ${TEMPLATES.length} taktik + Club DNA`;
team.onchange=loadTeam;preset.onchange=load;['support','lineSlider','compactSlider'].forEach(id=>$(id).oninput=updateSliders);$('play').onclick=play;$('edit').onclick=()=>{edit=!edit;$('edit').textContent=edit?'✓ SELESAI':'✥ EDIT';$('editBadge').style.display=edit?'block':'none';toastMsg(edit?'Geser pemain di lapangan.':'Mode edit dimatikan.')};$('save').onclick=save;window.addEventListener('resize',drawRoute);loadTeam();
