// ===== v1.3 Match Lab =====
const matchOppTeam=$('matchOppTeam'),matchOppPreset=$('matchOppPreset'),matchPitch=$('matchPitch'),matchPlayers=$('matchPlayers'),matchOpponents=$('matchOpponents'),matchBall=$('matchBall'),matchRoute=$('matchRoute'),matchBadge=$('matchBadge');
let matchState='NORMAL',matchRec=null,matchOpp=null,matchEvents=[],matchRAF=null,matchPlayerEls=[],matchOppEls=[],matchIntercept=-1,matchInterceptor=-1;
TEAMS.forEach(t=>matchOppTeam.add(new Option(t.name,t.name)));matchOppTeam.value='Real Madrid';
function makePresetForTeam(teamDef,value){
  if(value==='dna'){const t=clone(TEMPLATES.find(x=>x.name===teamDef.dnaTemplate)||TEMPLATES[0]);applyDna(t.s,teamDef.dnaType);t.clubDna=true;t.title='★ CLUB DNA • '+t.name;return t}
  const t=clone(TEMPLATES[+value||0]);t.clubDna=false;t.title=t.name;return t;
}
function loadMatchOpp(){const td=TEAMS.find(t=>t.name===matchOppTeam.value)||TEAMS[0];matchOppPreset.innerHTML='';matchOppPreset.add(new Option('★ '+td.dnaTemplate+' • CLUB DNA','dna'));TEMPLATES.forEach((t,i)=>matchOppPreset.add(new Option(t.form+' • '+t.name,i)));matchOppPreset.value='dna';matchAnalyze()}
function matchSyncOur(){if(!currentTeam||!current)return;$('matchOur').innerHTML=`${currentTeam.name} • ${current.form}<br><span style="font-size:11px;color:var(--muted)">${current.title}</span>`}
function findRecommended(keys){for(const k of keys){const n=k.toLowerCase();const t=TEMPLATES.find(x=>(x.name+' '+x.arch).toLowerCase().includes(n));if(t)return clone(t)}return clone(TEMPLATES[0])}
function matchAnalyze(){
  if(!currentTeam||!current)return;matchSyncOur();const td=TEAMS.find(t=>t.name===matchOppTeam.value)||TEAMS[0];matchOpp=makePresetForTeam(td,matchOppPreset.value);const s=matchOpp.s,txt=(matchOpp.name+' '+matchOpp.arch+' '+td.style).toLowerCase();let preferred,attack,defend,keyBattle,rs=4,rl=5,rc=8;
  if(matchState==='TERTINGGAL'){preferred=['Ultra Attack','High Press','Wide Overload','Gegenpress'];attack='Naikkan jumlah pemain di sepertiga akhir, overload sisi bola, rebut second ball, lalu cari cut-back.';defend='Tekan tinggi tetapi sisakan dua pemain + DMF sebagai rest-defence.';keyBattle='Kecepatan sirkulasi setelah recovery bola.';rl=8}
  else if(matchState==='UNGGUL'){preferred=['Mid Block','Balanced','Low Block Counter','Control 3-5-2'];attack='Tetap simpan outlet CF/winger. Jangan bertahan total agar lawan tidak bebas menaikkan semua pemain.';defend='Jaga blok rapat dan press dengan DMF/CMF sebelum CB keluar.';keyBattle='Ruang di depan CB dan area cut-back.';rl=4;rc=9;rs=5}
  else if(s.line>=7){preferred=['Rapid Transition','Vertical Counter','Narrow Counter','Direct Duo'];attack='Garis lawan tinggi: dua umpan aman lalu through/lofted-through ke ruang belakang FB/CB.';defend='Reset ke DMF/GK bila jalur vertikal tertutup, lalu serang sisi yang ditinggalkan presser.';keyBattle='Timing runner sebelum CB sempat berbalik.'}
  else if(s.compact>=8&&s.cont==='Center'){preferred=['Wide Overload','Quick Wing','Wingback Transition','Positional 3-2-4-1'];attack='Blok lawan rapat di tengah: switch play, buat 2v1 di flank, lalu cut-back.';defend='Saat kehilangan bola di sayap, tutup jalur pertama ke AMF/CF.';keyBattle='Switch play dan third-man run di half-space.';rl=6}
  else if(s.b==='Long Pass'||txt.includes('direct')||txt.includes('route one')){preferred=['Balanced','Mid Block','Control 3-5-2','Low Block Counter'];attack='Menangkan second ball lalu gunakan pass pertama yang aman sebelum counter.';defend='Turunkan garis sedikit dan rapatkan CB–DMF; jangan naikkan dua fullback bersamaan.';keyBattle='Second ball di depan lini belakang.';rl=4;rc=9}
  else if(s.area==='Wide'||txt.includes('wing')){preferred=['Balanced','Mid Block','Narrow Press','Gegenpress'];attack='Serang ruang di belakang fullback/wingback setelah recovery.';defend='Cegah 2v1 di sisi dan lindungi cut-back.';keyBattle='Duel flank dan perlindungan area cut-back.';rc=7}
  else if(s.a==='Possession Game'||txt.includes('tiki')||txt.includes('positional')){preferred=['Mid Block','Narrow Press','Gegenpress','Vertical Counter'];attack='Biarkan sirkulasi di area aman, rebut di tengah lalu vertikal cepat sebelum rest-defence pulih.';defend='Tutup penerima di antara lini, bukan mengejar bola.';keyBattle='Passing lane ke AMF/false 9.';rc=9}
  else {preferred=['Balanced','Vertical Counter','Possession Triangle'];attack='Bangun aman, identifikasi sisi longgar, lalu percepat ketika gelandang menghadap depan.';defend='Pertahankan shape dan pressure kedua ketika lawan sudah menghadap samping/belakang.';keyBattle='Ruang di antara lini.'}
  matchRec=findRecommended(preferred);let threat=42+(s.press==='Aggressive'?10:0)+(s.d==='Frontline Pressure'?7:0)+(s.line>=7?7:0)+(s.compact>=8?7:0)+(s.a==='Possession Game'?4:0)+(txt.includes('counter')||txt.includes('transition')?5:0);threat=Math.max(35,Math.min(92,threat));const label=threat>=78?'TINGGI':threat>=62?'SEDANG–TINGGI':threat>=48?'SEDANG':'TERKONTROL';
  $('matchThreat').textContent=`THREAT ${threat} • ${label}`;$('matchThreat').style.background=threat>=75?'#5f1d2b':threat>=60?'#5b3b1b':'#1c4b37';$('matchRecommend').innerHTML=`COUNTER • ${matchRec.form}<br>${matchRec.name}`;
  $('matchReport').textContent=`SCAN LAWAN\n${td.name} • ${matchOpp.form} • ${matchOpp.title}\nPressure ${s.press} • Defensive Line ${s.line}/10 • Compactness ${s.compact}/10 • Build Up ${s.b}.\n\n⚔ RENCANA MENYERANG\n${attack}\n\n🛡 RENCANA BERTAHAN\n${defend}\n\n⚙ SETTING AWAL\nSupport Range ${rs}/10 • Defensive Line ${rl}/10 • Compactness ${rc}/10.\n\n★ KEY BATTLE\n${keyBattle}`;
  matchRenderBoard();
}
function mName(role){return (NAMES[currentTeam.name]||{})[role]||role}
function matchRenderBoard(){
  if(!matchRec||!matchOpp)return;matchCancel();matchPlayerEls=[];matchOppEls=[];matchPlayers.innerHTML='';matchOpponents.innerHTML='';matchRoute.innerHTML='';matchBall.style.display='none';matchBadge.textContent='READY • 11v11';matchEvents=buildEvents(matchRec);
  matchRec.pos.forEach((p,i)=>{const el=document.createElement('div');el.className='mplayer';el.innerHTML=`<div class="mdot">${initials(mName(p[0]))}</div><div class="mlabel">${mName(p[0])}</div>`;el.style.left=p[1]*100+'%';el.style.top=p[2]*100+'%';matchPlayers.appendChild(el);matchPlayerEls.push(el)});
  matchOpp.pos.forEach((p,i)=>{const el=document.createElement('div');el.className='mopp';el.innerHTML=`<div class="mdot">${p[0]}</div>`;el.style.left=(1-p[1])*100+'%';el.style.top=(1-p[2])*100+'%';matchOpponents.appendChild(el);matchOppEls.push(el)});matchDrawRoute();
}
function matchDrawRoute(){const w=matchPitch.clientWidth,h=matchPitch.clientHeight;matchRoute.setAttribute('viewBox',`0 0 ${w} ${h}`);matchRoute.innerHTML='';matchEvents.forEach(e=>{const a=matchRec.pos[e.from],b=e.to>=0?matchRec.pos[e.to]:['',e.tx,e.ty],path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${a[1]*w} ${a[2]*h} L ${b[1]*w} ${b[2]*h}`);path.setAttribute('fill','none');path.setAttribute('stroke','#ffffff42');path.setAttribute('stroke-width','1.5');path.setAttribute('stroke-dasharray','6 7');matchRoute.appendChild(path)})}
function segDistance(ax,ay,bx,by,px,py){const vx=bx-ax,vy=by-ay,len=vx*vx+vy*vy;let t=len<1e-6?0:((px-ax)*vx+(py-ay)*vy)/len;t=Math.max(0,Math.min(1,t));const qx=ax+t*vx,qy=ay+t*vy;return [Math.hypot(px-qx,py-qy),t]}
function findMatchIntercept(){let threshold=.036+matchOpp.s.compact*.0022+(matchOpp.s.press==='Aggressive'?.010:0)+(matchOpp.s.d==='Frontline Pressure'?.006:0)+(matchRec.s.support>=7?.006:0);for(let ei=0;ei<matchEvents.length;ei++){const e=matchEvents[ei];if(['SHOOT','CROSS','LONG PASS'].includes(e.type)||e.to<0)continue;const a=matchRec.pos[e.from],b=matchRec.pos[e.to];let best=9,bi=-1;matchOpp.pos.forEach((o,oi)=>{if(o[0]==='GK')return;const d=segDistance(a[1],a[2],b[1],b[2],1-o[1],1-o[2]);if(d[1]>.16&&d[1]<.90&&d[0]<best){best=d[0];bi=oi}});const local=threshold+(e.type==='THROUGH PASS'?.010:0)-(e.type==='ONE-TWO'?.004:0);if(bi>=0&&best<local)return[ei,bi]}return[-1,-1]}
function mOurPoint(i,phase){const p=matchRec.pos[i],role=p[0],env=Math.sin(Math.PI*phase);let dy=role==='GK'?0:role.includes('WF')||role.includes('AMF')||role==='CF'||role==='SS'?-.08:role.includes('MF')||role==='DMF'?-.045:-.025;return{x:Math.max(.04,Math.min(.96,p[1])),y:Math.max(.05,Math.min(.95,p[2]+dy*env))}}
function matchPlay(){
  if(!matchRec||!matchOpp){matchAnalyze();return}matchCancel();[matchIntercept,matchInterceptor]=findMatchIntercept();matchOppEls.forEach((x,i)=>x.classList.toggle('intercept',i===matchInterceptor));const limit=matchIntercept>=0?matchIntercept:matchEvents.length-1,used=matchEvents.slice(0,limit+1),total=used.reduce((a,e)=>a+e.dur,0),start=performance.now(),dur=Math.max(4300,total*780);matchBall.style.display='block';
  function f(now){const elapsed=Math.min(1,(now-start)/dur),unit=elapsed*total,phase=unit/total;let cursor=0,idx=used.length-1,local=1;for(let i=0;i<used.length;i++){if(unit<=cursor+used[i].dur||i===used.length-1){idx=i;local=Math.max(0,Math.min(1,(unit-cursor)/used[i].dur));break}cursor+=used[i].dur}const e=used[idx];matchPlayerEls.forEach((el,i)=>{const q=mOurPoint(i,phase);el.style.left=q.x*100+'%';el.style.top=q.y*100+'%'});let a=mOurPoint(e.from,phase),b;if(matchIntercept===idx&&matchInterceptor>=0){const o=matchOpp.pos[matchInterceptor];b={x:1-o[1],y:1-o[2]}}else if(e.to>=0)b=mOurPoint(e.to,phase);else b={x:e.tx,y:e.ty};let u=e.type==='THROUGH PASS'?1-Math.pow(1-local,2):local*local*(3-2*local);const bx=a.x+(b.x-a.x)*u,by=a.y+(b.y-a.y)*u;matchBall.style.left=bx*100+'%';matchBall.style.top=by*100+'%';matchOppEls.forEach((el,i)=>{const o=matchOpp.pos[i];let ox=1-o[1],oy=1-o[2];if(o[0]!=='GK'){const dx=bx-ox,dy=by-oy,dist=Math.hypot(dx,dy),pf=matchOpp.s.press==='Aggressive'?.13:.075;if(dist<.48){ox+=dx*pf;oy+=dy*pf}}el.style.left=ox*100+'%';el.style.top=oy*100+'%'});matchBadge.textContent=(matchIntercept===idx&&local>.58)?'INTERCEPTED':e.type;if(elapsed<1)matchRAF=requestAnimationFrame(f);else{matchBadge.textContent=matchIntercept>=0?'INTERCEPTED • PASSING LANE CLOSED':'CHANCE CREATED • PATTERN WORKS';setTimeout(()=>matchRenderBoard(),1700)}}matchRAF=requestAnimationFrame(f)
}
function matchCancel(){if(matchRAF)cancelAnimationFrame(matchRAF);matchRAF=null}
function applyMatchTactic(){if(!matchRec)return;const idx=TEMPLATES.findIndex(x=>x.name===matchRec.name);if(idx<0)return;preset.value=String(idx);load();document.querySelector('[data-tab="tabTactics"]').click();toastMsg('Counter tactic diterapkan ke Tactical Lab.')}
matchOppTeam.onchange=loadMatchOpp;matchOppPreset.onchange=matchAnalyze;$('matchAnalyze').onclick=matchAnalyze;$('matchPlay').onclick=matchPlay;$('matchApply').onclick=applyMatchTactic;document.querySelectorAll('.stateBtn').forEach(b=>b.onclick=()=>{matchState=b.dataset.state;document.querySelectorAll('.stateBtn').forEach(x=>x.classList.toggle('active',x===b));matchAnalyze()});window.addEventListener('resize',()=>matchRec&&matchDrawRoute());loadMatchOpp();matchSyncOur();
